# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-08 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jgram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('bio', models.TextField()),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jgram.Followers')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jgram.Image')),
            ],
        ),
    ]
