# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-13 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jgram', '0008_auto_20190312_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
