# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-13 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jgram', '0009_remove_profile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
