# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-13 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jgram', '0010_auto_20190313_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
