# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-13 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jgram', '0011_auto_20190313_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
